version: '3'
services:
  app:
    image: abihf/video-upscaler:latest
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - TEMP_DIR=/media/data/upscaler
      - NVIDIA_DRIVER_CAPABILITIES=all
    user: "1000"
    group_add:
      - "1000"
    volumes:
      - /media/data:/media/data
      - /home/abi/models-cache:/models/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  ui:
    image: hibiken/asynqmon
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
